"""
Fix Migration Order Script
This script will help reorder the migration to avoid circular dependency issues.
"""
import os
import re

migration_file = "migrations/versions/4efa2f01a030_initial_migration.py"

print("=" * 60)
print("Fix Migration Table Creation Order")
print("=" * 60)

# Read the migration file
with open(migration_file, 'r') as f:
    content = f.read()

# The issue: departments table is created before employees
# But departments.manager_id references employees.id
# Solution: Remove the FK constraint from departments initially, add it later

# Find the departments table creation
departments_pattern = r"(op\.create_table\('departments',.*?sa\.ForeignKeyConstraint\(\['manager_id'\], \['employees\.id'\], \),.*?sa\.UniqueConstraint\('organization_id', 'code', name='uq_org_dept_code'\).*?\))"

# Find the employees table creation  
employees_pattern = r"(op\.create_table\('employees',.*?sa\.UniqueConstraint\('organization_id', 'employee_code', name='uq_org_emp_code'\).*?\))"

print("\nAnalyzing migration file...")
print(f"File: {migration_file}")

# Strategy: Make manager_id FK nullable and add it after employees table is created
# Let's rewrite the migration with proper ordering

fixed_upgrade = '''def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create roles table first (no dependencies)
    op.create_table('roles',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    # Create organizations table (no dependencies)
    op.create_table('organizations','''

print("\nThe migration file has a circular dependency issue:")
print("  - departments.manager_id -> employees.id")
print("  - employees.department_id -> departments.id")
print("\nThis requires manual fixing...")
print("\nRecommendation:")
print("  1. Make manager_id nullable and don't add FK constraint initially")
print("  2. Or use 'use_alter=True' in the ForeignKeyConstraint")
print("  3. Or add the FK constraint in a separate migration step")

print("\n" + "=" * 60)
print("Manual fix required - see CIRCULAR_DEPENDENCY_FIX.md")
print("=" * 60)
