"""Add subscription_plan and enabled_features fields

Revision ID: 5f3e2a1b8c9d
Revises: 470dc38dbfa6
Create Date: 2025-12-26 15:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f3e2a1b8c9d'
down_revision = '470dc38dbfa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add subscription_plan column
    op.add_column('organizations', 
        sa.Column('subscription_plan', sa.String(length=20), nullable=False, server_default='free')
    )
    
    # Add enabled_features column as JSON
    op.add_column('organizations', 
        sa.Column('enabled_features', sa.JSON(), nullable=True)
    )
    
    # Set default values for existing records
    op.execute("""
        UPDATE organizations 
        SET enabled_features = '{"employee_attendance": true}'::json
        WHERE enabled_features IS NULL
    """)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove the added columns
    op.drop_column('organizations', 'enabled_features')
    op.drop_column('organizations', 'subscription_plan')
    
    # ### end Alembic commands ###