"""Initial_migration

Revision ID: 470dc38dbfa6
Revises: 
Create Date: 2025-12-26 11:44:14.484872

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '470dc38dbfa6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('subscription_tier', sa.String(length=20), nullable=False),
    sa.Column('organization_type', sa.String(length=50), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('working_hours', sa.JSON(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_organizations_name'), ['name'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('user_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login_id', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('employee_id', sa.String(length=64), nullable=True),
    sa.Column('tower', sa.String(length=64), nullable=True),
    sa.Column('building_name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_details_login_id'), ['login_id'], unique=True)

    op.create_table('visitor_details',
    sa.Column('aadhaar_id', sa.String(length=12), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('purpose_of_visit', sa.String(length=255), nullable=True),
    sa.Column('host_to_visit', sa.String(length=120), nullable=True),
    sa.Column('floors', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('towers', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('duration_from', sa.Date(), nullable=True),
    sa.Column('duration_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('aadhaar_id')
    )
    op.create_table('departments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manager_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_org_dept_code')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_organization_id'), ['organization_id'], unique=False)

    op.create_table('locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('building', sa.String(length=128), nullable=True),
    sa.Column('floor', sa.String(length=50), nullable=True),
    sa.Column('area', sa.String(length=128), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_org_location_name')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_organization_id'), ['organization_id'], unique=False)

    op.create_table('shifts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('grace_period_minutes', sa.Integer(), nullable=True),
    sa.Column('working_days', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shifts_organization_id'), ['organization_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('visitor_images',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('aadhaar_id', sa.String(length=12), nullable=False),
    sa.Column('angle', sa.String(length=16), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aadhaar_id'], ['visitor_details.aadhaar_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aadhaar_id', 'angle', name='uq_visitor_angle')
    )
    op.create_table('visitors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('visitor_name', sa.String(length=255), nullable=False),
    sa.Column('mobile_number', sa.String(length=20), nullable=False),
    sa.Column('purpose_of_visit', sa.String(length=500), nullable=False),
    sa.Column('allowed_floor', sa.String(length=100), nullable=False),
    sa.Column('check_in_time', sa.DateTime(), nullable=False),
    sa.Column('check_out_time', sa.DateTime(), nullable=True),
    sa.Column('is_checked_in', sa.Boolean(), nullable=True),
    sa.Column('current_floor', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitors_organization_id'), ['organization_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('idx_org_created', ['organization_id', 'created_at'], unique=False)
        batch_op.create_index('idx_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('cameras',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('camera_type', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('source_config', sa.JSON(), nullable=True),
    sa.Column('fps', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('confidence_threshold', sa.Float(), nullable=True),
    sa.Column('liveness_check_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_org_camera_name')
    )
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cameras_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cameras_organization_id'), ['organization_id'], unique=False)

    op.create_table('employees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('employee_code', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('emergency_contact', sa.JSON(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('designation', sa.String(length=128), nullable=True),
    sa.Column('employment_type', sa.String(length=20), nullable=True),
    sa.Column('shift_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'employee_code', name='uq_org_emp_code')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_user_id'), ['user_id'], unique=True)

    op.create_table('images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('image_base64', sa.Text(), nullable=False),
    sa.Column('image_type', sa.String(length=50), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=50), nullable=True),
    sa.Column('captured_by', sa.String(length=36), nullable=True),
    sa.Column('capture_device', sa.String(length=255), nullable=True),
    sa.Column('capture_location', sa.String(length=255), nullable=True),
    sa.Column('primary', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['captured_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.create_index('idx_image_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('idx_image_org_entity', ['organization_id', 'entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_images_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_images_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_images_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_images_organization_id'), ['organization_id'], unique=False)

    op.create_table('visitor_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('visitor_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('current_floor', sa.String(length=100), nullable=False),
    sa.Column('allowed_floor', sa.String(length=100), nullable=False),
    sa.Column('alert_time', sa.DateTime(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visitor_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitor_alerts_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitor_alerts_visitor_id'), ['visitor_id'], unique=False)

    op.create_table('visitor_movement_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('visitor_id', sa.String(length=36), nullable=False),
    sa.Column('floor', sa.String(length=100), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visitor_movement_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitor_movement_logs_visitor_id'), ['visitor_id'], unique=False)

    op.create_table('attendance_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(), nullable=True),
    sa.Column('check_out_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('work_hours', sa.Float(), nullable=True),
    sa.Column('location_check_in', sa.JSON(), nullable=True),
    sa.Column('location_check_out', sa.JSON(), nullable=True),
    sa.Column('device_info', sa.JSON(), nullable=True),
    sa.Column('face_match_confidence', sa.Float(), nullable=True),
    sa.Column('liveness_verified', sa.Boolean(), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'date', name='uq_employee_date')
    )
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.create_index('idx_emp_date', ['employee_id', 'date'], unique=False)
        batch_op.create_index('idx_org_date', ['organization_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_organization_id'), ['organization_id'], unique=False)

    op.create_table('face_embeddings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('embedding_vector', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('face_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_face_embeddings_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_face_embeddings_organization_id'), ['organization_id'], unique=False)

    op.create_table('leave_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('leave_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_days', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_requests_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_requests_organization_id'), ['organization_id'], unique=False)

    op.create_table('presence_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=True),
    sa.Column('camera_id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('liveness_verified', sa.Boolean(), nullable=True),
    sa.Column('liveness_score', sa.Float(), nullable=True),
    sa.Column('face_bbox', sa.JSON(), nullable=True),
    sa.Column('face_quality_score', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('attendance_record_id', sa.String(length=36), nullable=True),
    sa.Column('device_info', sa.JSON(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('is_unknown_face', sa.Boolean(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('anomaly_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attendance_record_id'], ['attendance_records.id'], ),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('presence_events', schema=None) as batch_op:
        batch_op.create_index('idx_camera_timestamp', ['camera_id', 'timestamp'], unique=False)
        batch_op.create_index('idx_emp_timestamp', ['employee_id', 'timestamp'], unique=False)
        batch_op.create_index('idx_org_timestamp', ['organization_id', 'timestamp'], unique=False)
        batch_op.create_index('idx_review_status', ['review_status', 'organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_presence_events_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_presence_events_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_presence_events_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_presence_events_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_presence_events_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presence_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presence_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_presence_events_organization_id'))
        batch_op.drop_index(batch_op.f('ix_presence_events_location_id'))
        batch_op.drop_index(batch_op.f('ix_presence_events_employee_id'))
        batch_op.drop_index(batch_op.f('ix_presence_events_camera_id'))
        batch_op.drop_index('idx_review_status')
        batch_op.drop_index('idx_org_timestamp')
        batch_op.drop_index('idx_emp_timestamp')
        batch_op.drop_index('idx_camera_timestamp')

    op.drop_table('presence_events')
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_requests_organization_id'))
        batch_op.drop_index(batch_op.f('ix_leave_requests_employee_id'))

    op.drop_table('leave_requests')
    with op.batch_alter_table('face_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_face_embeddings_organization_id'))
        batch_op.drop_index(batch_op.f('ix_face_embeddings_employee_id'))

    op.drop_table('face_embeddings')
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_records_organization_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_records_employee_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_records_date'))
        batch_op.drop_index(batch_op.f('ix_attendance_records_camera_id'))
        batch_op.drop_index('idx_org_date')
        batch_op.drop_index('idx_emp_date')

    op.drop_table('attendance_records')
    with op.batch_alter_table('visitor_movement_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitor_movement_logs_visitor_id'))

    op.drop_table('visitor_movement_logs')
    with op.batch_alter_table('visitor_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitor_alerts_visitor_id'))
        batch_op.drop_index(batch_op.f('ix_visitor_alerts_organization_id'))

    op.drop_table('visitor_alerts')
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_images_organization_id'))
        batch_op.drop_index(batch_op.f('ix_images_entity_type'))
        batch_op.drop_index(batch_op.f('ix_images_entity_id'))
        batch_op.drop_index(batch_op.f('ix_images_created_at'))
        batch_op.drop_index('idx_image_org_entity')
        batch_op.drop_index('idx_image_entity')

    op.drop_table('images')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_user_id'))
        batch_op.drop_index(batch_op.f('ix_employees_organization_id'))
        batch_op.drop_index(batch_op.f('ix_employees_full_name'))
        batch_op.drop_index(batch_op.f('ix_employees_department_id'))

    op.drop_table('employees')
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cameras_organization_id'))
        batch_op.drop_index(batch_op.f('ix_cameras_location_id'))

    op.drop_table('cameras')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_index('idx_user_created')
        batch_op.drop_index('idx_org_created')
        batch_op.drop_index('idx_entity')

    op.drop_table('audit_logs')
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitors_organization_id'))

    op.drop_table('visitors')
    op.drop_table('visitor_images')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role_id'))
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shifts_organization_id'))

    op.drop_table('shifts')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_organization_id'))

    op.drop_table('locations')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_organization_id'))

    op.drop_table('departments')
    op.drop_table('visitor_details')
    with op.batch_alter_table('user_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_details_login_id'))

    op.drop_table('user_details')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))

    op.drop_table('roles')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_name'))
        batch_op.drop_index(batch_op.f('ix_organizations_code'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
